---
title: "Enrichment_Analysis"
author: "Nick Kron"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load Packages

```{r load packages, echo=FALSE, warning=FALSE,message=FALSE}

# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("topGO")

#library(topGO)


# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("clusterProfiler")

library(clusterProfiler)
library(pathview)
library(org.Hs.eg.db)
library(ComplexHeatmap)

#install.packages("tidyverse")
library(tidyverse)

```

<!-- Define function to summarize count table to a group level -->
```{r, echo=FALSE, message=FALSE, warning = FALSE}
summarize_group <- function(ma, group){
    counts_group = t(sapply(rownames(ma), function(g){
        sapply(levels(group), function(i){
            idx = which(group == i)
            mean(ma[g, idx], na.rm = TRUE)
        })
    }))
    colnames(counts_group) = levels(group)
    counts_group
}
```

<!-- Define functions to get maximal log 2 fold change from expression matrix -->
```{r, echo=FALSE, message=FALSE, warning = FALSE}
maxL2FC <- function(x, log2 = FALSE){
  #' Get maximal log2 Fold Change of input vector
  #'
  #' Takes a vector and calculates the maximal log2 fold change of a sequence of values.
  #' If only 2 values are provided, collapses to normal log2 fold change calculation.
  #'
  #' @param x numeric. A vector that is assumed to be in order. Must have at least 2 components.
  #' @param log2 boolean. Specify if input values need to be log transformed, TRUE if yes. Default FALSE.
  #' @return numeric. The maximal log2 fold change of the input vector. 
  
  #check user input
  if(!is.numeric(x)){
    stop("Input is not of type numeric")
  }
  if(length(x) < 2){
    stop("Input must have at least 2 values")
  }
    #rising trend
    if( match(max(x), x) > match(min(x), x) ){
      a = min(x)
      b = max(x)
    }
    #falling trend
    else if ( match(min(x), x) > match(max(x), x) ){
      a = max(x)
      b = min(x)
    }
    #log2(value +1) transform to get log fold change
    if(log2 == TRUE){
      log(b+1,2) - log(a+1,2)
    }
    else{
      b-a
    }

}


getMaxL2FC <- function(em, byRow = TRUE, log2 = FALSE){
  #' Get maximal log2 Fold Change of input expression matrix
  #'
  #' Takes an expression matrix and calculates the maximal log2 fold change per gene.
  #'
  #' @param em numeric. An expression matrix.
  #' @param byRow boolean. If TRUE, matrixs is gene by sample, ie rows represent genes. FALSE will evaluate by column.
  #' @param log2 boolean. Specify if input values need to be log transformed, TRUE if yes. Default FALSE.
  #' @return numeric. A vector containing the maximal log2 fold change of an input matrix. 
  
  if(! (is.matrix(em) | is.data.frame(em) ) ){
    stop("Input must be an expression matrix.")
  }
  em <- as.matrix(em)
  
  if(byRow == TRUE){
    m = 1L
  }
  else{
    m = 2L
  }
  apply(em, MARGIN = m, FUN = maxL2FC)
  
}


```

<!-- Define function to summarize count table to a group level -->
```{r, echo=FALSE, message=FALSE, warning = FALSE}
summarize_group <- function(ma, group){
    counts_group = t(sapply(rownames(ma), function(g){
        sapply(levels(group), function(i){
            idx = which(group == i)
            mean(ma[g, idx], na.rm = TRUE)
        })
    }))
    colnames(counts_group) = levels(group)
    counts_group
}
```

## Load data files

```{r load files, echo=FALSE, warning=FALSE,message=FALSE}

load(file = "../data/r_data/res.pvc.R") 
load(file = "../data/r_data/res.bsc.R") 
load(file = "../data/r_data/annot.R") 

```

## Give unique, arbitrary names to each cluster

```{r look at clusters, echo=FALSE, warning=FALSE,message=FALSE}


bsc_clust <- c(
  "1" = "B1",
  "2" = "B3",
  "3" = "B2",
  "5" = "B4"
)


res.bsc_patterns$clust <- bsc_clust[as.character(res.bsc_patterns$cluster)]
res.bsc_clusters$clust <- bsc_clust[as.character(res.bsc_clusters$cluster)]

res.bsc_clusters <- res.bsc_clusters %>% mutate( direction = 
                               ifelse(clust %in% c("B1","B2"), "UP","DOWN")
                               ) 

bsc_clusters <- split(res.bsc_clusters, f = res.bsc_clusters$clust)
names(bsc_clusters) <- unique(res.bsc_clusters$clust)

# res.bsc_patterns %>% ggplot(data = ., aes(x = time, y = value)) +
#   geom_boxplot(alpha = 0, color = "cornflowerblue") +
#   geom_point(
#     data = res.bsc_patterns,
#     mapping = aes(x = jitter(as.numeric(time)), y = value),
#     alpha = 0.1,
#     color = "cornflowerblue"
#   ) +
#   geom_smooth(
#     data = res.bsc_patterns,
#     mapping = aes(x = as.numeric(time), y = value),
#     method = "loess",
#     se = FALSE,
#     size = 2,
#     color = "cornflowerblue"
#   ) +
#   facet_wrap(facets = "clust")

#######


pvc_clust <- c(
  "1" = "P1",
  "3" = "P2",
  "5" = "P3",
  "4" = "P4",
  "8" = "P5"
)


res.pvc_patterns$clust <- pvc_clust[as.character(res.pvc_patterns$cluster)]
res.pvc_clusters$clust <- pvc_clust[as.character(res.pvc_clusters$cluster)]

pvc_clusters <- split(res.pvc_clusters, f = res.pvc_clusters$clust)
names(pvc_clusters) <- unique(res.pvc_clusters$clust)

res.pvc_clusters <- res.pvc_clusters %>% mutate( direction = 
                               ifelse(clust %in% c("P1","P2","P3"), "UP","DOWN")
                               ) 

# res.pvc_patterns %>% ggplot(data = ., aes(x = time, y = value)) +
#   geom_boxplot(alpha = 0, color = "tomato") +
#   geom_point(
#     data = res.pvc_patterns,
#     mapping = aes(x = jitter(as.numeric(time)), y = value),
#     alpha = 0.1,
#     color = "tomato"
#   ) +
#   geom_smooth(
#     data = res.pvc_patterns,
#     mapping = aes(x = as.numeric(time), y = value),
#     method = "loess",
#     se = FALSE,
#     size = 2,
#     color = "tomato"
#   ) +
#   facet_wrap(facets = "clust")



```

## Build Full Annotation for each tissue

```{r}

# combine LRT padj, cluster ID, aplcal tx, prot, product, human ortholog, human ortholog name, average expression per age group

load(file = "../data/r_data/cor_TPM.bsc.R")
load(file = "../data/r_data/cor_TPM.pvc.R")
load(file = "../data/r_data/metadata.R")

res.bsc_anot <- res.bsc %>%
  rownames_to_column("tx") %>%
  select(tx, padj) %>%
  left_join(., AcTxAnot) %>%
  select(tx, padj, prot, product, ko, Entry, Gene_names, Protein_names) %>%
  left_join(.,
            res.bsc_clusters %>% select(genes, clust, direction),
            by = c("tx" = "genes")) %>%
  select(tx, padj, clust, direction, everything()) %>%
  rename(
    cluster = "clust",
    Uniprot_ID = "Entry",
    Human_ortholog = "Gene_names",
    Ortholog_names = "Protein_names"
  ) %>%
  inner_join(
    .,
    cor_TPM.bsc %>% rownames_to_column("tx") %>% pivot_longer(
      cols = -tx,
      names_to = "Seq_ID",
      values_to = "cor_TPM"
    ) %>%
      inner_join(., metadata %>% select(Seq_ID, Age)) %>% group_by(tx, Age) %>%
      summarise(mean_TPM = mean(cor_TPM)) %>% pivot_wider(names_from = Age, values_from = mean_TPM)
  )



res.pvc_anot <- res.pvc %>%
  rownames_to_column("tx") %>%
  select(tx, padj) %>%
  left_join(., AcTxAnot) %>%
  select(tx, padj, prot, product, ko, Entry, Gene_names, Protein_names) %>%
  left_join(.,
            res.pvc_clusters %>% select(genes, clust, direction),
            by = c("tx" = "genes")) %>%
  select(tx, padj, clust, direction, everything()) %>%
  rename(
    cluster = "clust",
    Uniprot_ID = "Entry",
    Human_ortholog = "Gene_names",
    Ortholog_names = "Protein_names"
  ) %>%
  left_join(
    .,
    cor_TPM.pvc %>% rownames_to_column("tx") %>% pivot_longer(
      cols = -tx,
      names_to = "Seq_ID",
      values_to = "cor_TPM"
    ) %>%
      inner_join(., metadata %>% select(Seq_ID, Age)) %>% group_by(tx, Age) %>%
      summarise(mean_TPM = mean(cor_TPM)) %>% pivot_wider(names_from = Age, values_from = mean_TPM)
  )


res.pvc_anot %>%
  filter(str_detect(string = Human_ortholog, pattern = "EIF2A"))

cor_TPM.pvc %>% rownames_to_column("tx") %>% pivot_longer(
      cols = -tx,
      names_to = "Seq_ID",
      values_to = "cor_TPM"
    ) %>%
  filter(tx %in% c("XM_005105060.2")) %>%
      inner_join(., metadata %>% select(Seq_ID, Age)) %>% group_by(tx, Age) %>%
  ggplot(data = ., aes(x = Age, y = cor_TPM)) + geom_point() + facet_wrap(facets = "tx")

write.table(res.bsc_anot, file = "../results/BSC_tx_results.tab", sep = "\t", quote = FALSE, row.names = FALSE)
write.table(res.pvc_anot, file = "../results/PVC_tx_results.tab", sep = "\t", quote = FALSE, row.names = FALSE)


```



## KEGG cluster enrichment

```{r KEGG enrichment BSC, echo=FALSE, warning=FALSE,message=FALSE}


 BSCKegg <- lapply(
  X = unique(res.bsc_clusters$clust),
  FUN = function(x) {
    y <- clusterProfiler::enrichKEGG(gene = (res.bsc_clusters %>% 
                                          inner_join(Tx2Prot2Kegg, by = c("genes" = "tx")) %>% 
                                          filter(clust == x))[,"ko"],
                                organism = "ko",
                                pvalueCutoff = 0.05)
    write.table(y, file = paste0("../results/KEGG/",x,".txt"), row.names = FALSE, quote = FALSE, sep = "\t")
    print(y)
  }
)

BSCKegg_dir <- lapply(
  X = c("UP","DOWN"),
  FUN = function(x) {
    y <-clusterProfiler::enrichKEGG(gene = (res.bsc_clusters %>% 
                                          inner_join(Tx2Prot2Kegg, by = c("genes" = "tx")) %>% 
                                          filter(direction == x))[,"ko"],
                                organism = "ko",
                                pvalueCutoff = 0.05)
    write.table(y, file = paste0("../results/KEGG/BSC_",x,".txt"), row.names = FALSE, quote = FALSE, sep = "\t")
    print(y)
  }
)



```


```{r KEGG enrichment BSC, echo=FALSE, warning=FALSE,message=FALSE}


 PVCKegg <- lapply(
  X = unique(res.pvc_clusters$clust),
  FUN = function(x) {
    y <- clusterProfiler::enrichKEGG(gene = (res.pvc_clusters %>% 
                                          inner_join(Tx2Prot2Kegg, by = c("genes" = "tx")) %>% 
                                          filter(clust == x))[,"ko"],
                                organism = "ko",
                                pvalueCutoff = 0.05)
    write.table(y, file = paste0("../results/KEGG/",x,".txt"), row.names = FALSE, quote = FALSE, sep = "\t")
    print(y)
  }
)

PVCKegg_dir <- lapply(
  X = c("UP","DOWN"),
  FUN = function(x) {
    y <- clusterProfiler::enrichKEGG(gene = (res.pvc_clusters %>% 
                                          inner_join(Tx2Prot2Kegg, by = c("genes" = "tx")) %>% 
                                          filter(direction == x))[,"ko"],
                                organism = "ko",
                                pvalueCutoff = 0.05)
    write.table(y, file = paste0("../results/KEGG/PVC_",x,".txt"), row.names = FALSE, quote = FALSE, sep = "\t")
    print(y)
  }
)





```


### Identify common KEGG pathways

```{r common KEGG}

inner_join(
read.table(file = "../results/KEGG/PVC_UP.txt", sep = "\t", header = TRUE)%>% dplyr::select(ID, Description, p.adjust),
read.table(file = "../results/KEGG/BSC_UP.txt", sep = "\t", header = TRUE)%>% dplyr::select(ID, Description, p.adjust),
by = c("ID", "Description"), 
suffix = c("_pvc","_bsc")
)

inner_join(
read.table(file = "../results/KEGG/PVC_DOWN.txt", sep = "\t", header = TRUE)%>% dplyr::select(ID, Description,p.adjust),
read.table(file = "../results/KEGG/BSC_DOWN.txt", sep = "\t", header = TRUE)%>% dplyr::select(ID, Description, p.adjust),
by = c("ID", "Description"), 
suffix = c("_pvc","_bsc")
)


```

### Get KEGG genes
```{r}


get_ko_genes <- function(clusters, ko=NULL){
  
  dat <- lapply(clusters, FUN = function(x){
    read.table(file = paste0("../results/KEGG/",x,".txt"), sep = "\t", header = TRUE) %>%
      mutate(clust = x)
  }) %>%
    do.call("rbind",.)%>%
  separate_rows(., geneID, sep = "/") %>%
  dplyr::select(ID, Description, geneID, clust) %>%
  inner_join(Tx2Prot2Kegg %>% 
  dplyr::select(tx,ko) %>% 
  filter(ko != "") %>% 
  inner_join(AcTxAnot  %>% dplyr::select(tx, Gene_names, Protein_names)),
  by = c("geneID"="ko")
  )%>% 
    unique()
  if(! is.null(ko)){
  dat <- dat  %>%
    filter(ID == ko)
  }

  dat
}


get_ko_genes(clusters = c("BSC_DOWN"), ko = "ko04721")


```

## View Kegg Pathways
```{r KEGG pathways}

###filter rows so that at least one time point has a lowest count greater than threshold

load(file = "../data/r_data/cor_TPM.bsc.R")
load(file = "../data/r_data/cor_TPM.pvc.R")
load(file = "../data/r_data/metadata.R")


kegg.bsc <- cor_TPM.bsc %>% as.data.frame() %>% 
  rownames_to_column("tx")%>% 
  pivot_longer(-tx,names_to = "Seq_ID", values_to = "log2Expr") %>%
  inner_join(metadata %>% select(Age, Seq_ID)) %>%
  group_by(tx, Age) %>%
  summarise(meanExpr = mean(log2Expr)) %>% ungroup() %>%
  inner_join(res.bsc %>% rownames_to_column("tx") %>% select(tx, padj)) %>% filter(padj <= 0.01) %>%
  inner_join(Tx2Prot2Kegg %>% select(ko, tx))%>% select(-c("tx", "padj"))%>%
  filter(ko != "")  %>%
  group_by(ko, Age) %>% mutate(sumExpr = sum(meanExpr)) %>%
  select(-meanExpr) %>%
  unique() %>%
  pivot_wider(names_from = Age, values_from = sumExpr) %>%
  column_to_rownames("ko") %>%
  getMaxL2FC() %>% data.frame(maxL2fc = .)

kegg.pvc <- cor_TPM.pvc %>% as.data.frame() %>% 
  rownames_to_column("tx")%>% 
  pivot_longer(-tx,names_to = "Seq_ID", values_to = "log2Expr") %>%
  inner_join(metadata %>% select(Age, Seq_ID)) %>%
  group_by(tx, Age) %>%
  summarise(meanExpr = mean(log2Expr)) %>% ungroup() %>%
  inner_join(res.pvc %>% rownames_to_column("tx") %>% select(tx, padj)) %>% filter(padj <= 0.01) %>%
  inner_join(Tx2Prot2Kegg %>% select(ko, tx))%>% select(-c("tx", "padj"))%>%
  filter(ko != "")  %>%
  group_by(ko, Age) %>% mutate(sumExpr = sum(meanExpr)) %>%
  select(-meanExpr) %>%
  unique() %>%
  pivot_wider(names_from = Age, values_from = sumExpr) %>%
  column_to_rownames("ko") %>%
  getMaxL2FC() %>% data.frame(maxL2fc = .)

```

## clusterProfiler GO cluster enrichment

```{r GO enrichment function, echo=FALSE, warning=FALSE,message=FALSE}

getGO <- function(uni,
           clusters,
           clust_ID,
           ontology = "BP",
           save = FALSE,
           simple = FALSE) {
    ##make sure user didn't specify an impossible option
    if (!ontology %in% c("BP", "MF", "CC")) {
      print("Unkown ontology selected, using BP")
      ontology = "BP"
    }
    
  genes <- clusters %>% dplyr::filter(clust_ID == clust) %>% inner_join(., AcTxAnot, by =c("genes" = "tx")) %>% unique()
  genes <- genes$Entry
  
    ## Get GO enrichment
    go <-
      enrichGO(
        gene          = genes,
        universe      = uni,
        OrgDb         = org.Hs.eg.db,
        keyType       = "UNIPROT",
        ont           = ontology,
        pvalueCutoff  = 0.05,
        qvalueCutoff  = 0.05,
        readable      = TRUE
      )
    
    ##Determine if user wants reduced output or not
    if (simple == TRUE) {
      go <-
        go %>% clusterProfiler::gofilter(., 5) %>% as.data.frame() %>% arrange(p.adjust)
      outfile = paste0("../results/cpGO/",
                       clust_ID,
                       "_",
                       ontology,
                       "_GO_level5.txt")
    }
    else{
      go <- go %>% as.data.frame() %>% arrange(p.adjust)
      outfile = paste0("../results/cpGO/",
                       clust_ID,
                       "_",
                       ontology,
                       "_GO.txt")
    }
    if (save == TRUE) {
      write.table(
        x = go,
        file = outfile,
        quote = FALSE,
        row.names = FALSE,
        sep = "\t"
      )
    }
    invisible(go)
  }
    


```


```{r Go enrichment for all clusters, echo=FALSE, warning=FALSE,message=FALSE}

### THIS IS SUPER SLOW, TRY TO DO ONLY ONCE
## //todo OPTIMIZE

uni <-  (AcTxAnot %>% unique() %>% filter(tx %in% rownames(res.bsc)))$Entry

lapply(unique(res.bsc_clusters$clust), function(x) {
  print(paste0("Processing:", x))
  enrichment <- lapply(c("BP", "MF", "CC"), function(y) {
    getGO(
      uni = uni,
      clusters = res.bsc_clusters,
      clust_ID = x,
      ontology = y,
      save = FALSE,
      simple = TRUE
    ) %>%
      as.data.frame() %>% mutate(ontology = y) %>% select(ontology, everything())
  }) %>% do.call("rbind", .)
  write.table(
    x = enrichment,
    file = paste0("../results/cpGO/", x, "_allGO.txt"),
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )
})

lapply(unique(res.pvc_clusters$clust), function(x) {
  print(paste0("Processing:", x))
  enrichment <- lapply(c("BP", "MF", "CC"), function(y) {
    getGO(
      uni =  uni,
      clusters = res.pvc_clusters,
      clust_ID = x,
      ontology = y,
      save = FALSE,
      simple = TRUE
    ) %>%
      as.data.frame() %>% mutate(ontology = y) %>% select(ontology, everything())
  }) %>%
    do.call("rbind", .)
  write.table(
    x = enrichment,
    file = paste0("../results/cpGO/", x, "_allGO.txt"),
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )
})


  
```


```{r, fig.width=10, fig.height= 25}


allCLusterGO <- lapply(
  X = c(paste0(rep("B", 4), seq(1, 4, 1)), paste0(rep("P", 4), seq(1, 5, 1))),
  FUN =  function(x) {
    read.table(
      file = paste0("../results/cpGO/", x, "_allGO.txt"),
      sep = "\t",
      header = TRUE,
      stringsAsFactors = FALSE
    ) %>% mutate(cluster = x)
  }
) %>% 
  do.call("rbind",.) %>% select(cluster, everything())

write.table(x = allCLusterGO, file = "../results/cpGO/allClusterGO.txt", quote = FALSE, row.names = FALSE, sep = "\t")

hbp <- allCLusterGO %>% select(ID,Description, cluster, ontology) %>%
  mutate(is.member = 1) %>%
  pivot_wider(., names_from = cluster, values_from = is.member) %>% 
  replace(., is.na(.), 0) %>%
  filter( ontology == "BP") %>%
  mutate(sum = rowSums(.[c("B1","B2","B3","B4","P1","P3","P4","P5")])) %>%
  filter(sum > 1) %>%
  mutate(GO = paste0(Description, " (", ID, ")")) %>%
  select(-c("ID","Description","ontology", "sum")) %>%
  column_to_rownames("GO") %>%
  ComplexHeatmap::Heatmap(matrix = .,
                          width = unit(5,"cm"),
                          row_names_gp = gpar( fontsize = 10),
                          heatmap_legend_param =  list(direction = "horizontal", side = "bottom")
                          )

draw(hbp, heatmap_legend_side = "bottom")


hm <- allCLusterGO %>% select(ID,Description, cluster, ontology) %>%
  mutate(is.member = 1) %>%
  filter(ontology == "BP") %>%
  pivot_wider(., names_from = cluster, values_from = is.member) %>% 
  replace(., is.na(.), 0) %>%
  mutate(GO = paste0(Description, " (", ID, ")")) %>%
  select(-c("ID","Description","ontology")) %>%
  column_to_rownames("GO") %>%
  ComplexHeatmap::Heatmap(matrix = .,
                          width = unit(5,"cm"),
                          row_names_gp = gpar( fontsize = 10),
                          heatmap_legend_param =  list(direction = "horizontal", side = "bottom")
                          )

draw(hm, heatmap_legend_side = "bottom")

```


##topGO GO cluster enrichment

```{r, echo=FALSE, message=FALSE, warning = FALSE, include= FALSE, out.width = '60%', eval = FALSE}

DEGClusterGO <- function(res, patterns, clust, ontology = "BP", plot = FALSE, save = FALSE) {
                geneUniverse <- as.numeric(rownames(res) %in% patterns[which(patterns$clust == clust),]$genes)
                names(geneUniverse) = rownames(res)
                
                library(topGO)
                GOdata <- new("topGOdata",
                              description = "GO analysis of sig genes in Full Dataset Tissue Specific model",
                              ontology = ontology, 
                              allGenes = geneUniverse, 
                              annot = annFUN.gene2GO,
                              geneSel = function(x){return(x > 0)},
                              gene2GO = AcTx2GO,
                              nodeSize = 10)
                
                resultFisher <- runTest(GOdata, algorithm = "elim", statistic = "fisher")
                
                tab <- GenTable(GOdata, raw.p.value = resultFisher, topNodes = length(resultFisher@score),
                                numChar = 120)
                
                grpGO <- as.data.frame(tab[1:length(tab[which(tab$raw.p.value <= 0.01),]$raw.p.value),][, c("Term","raw.p.value", "GO.ID", "Significant")])
                grpGO$raw.p.value <- as.numeric(as.character(grpGO$raw.p.value))
                grpGO$Term <- factor(grpGO$Term, levels = grpGO$Term[order(grpGO$raw.p.value, decreasing = TRUE)])
                grpGO <- grpGO %>% as.data.frame() %>% dplyr::select(GO.ID, raw.p.value, Significant, Term)
                
                
                if(save == TRUE){
                write.table(x = grpGO, file = paste0("../results/GO/",clust,"_",ontology,"_GO.txt"), sep = "\t", quote = FALSE, row.names = FALSE)
                }
                
                if(plot == TRUE){
                ggplot( data = grpGO,
                        aes(x = Term, y = -log(as.numeric(as.character(raw.p.value))))) +
                  geom_bar(stat = "identity", fill = "green3") +
                  geom_text(aes(label=paste0(GO.ID,", ", Significant),hjust=0, vjust = 0.25, y = 0.5), size = 2.5) +
                    coord_flip() +
                  labs(title = paste0("Cohort 77 Cluster", 
                       " ", clust, " GO Enrichment"), 
                       y = "-log p-value", 
                       x = ontology) +
                  #geom_hline(yintercept = -log(0.05)) +
                  geom_hline(yintercept = -log(0.01), linetype = 2)
                  # annotate("text",label = c(
                  #   #paste0(intToUtf8(0x03B1), " = 0.05"),
                  #   paste0(intToUtf8(0x03B1), " = 0.01")),
                  #   y = c(-log(0.01) + 0.35),
                  #   x = c(1,1) )
                  
                  if(save == TRUE){
                    ggsave(filename =  paste0("../results/GO/",clust,"_",ontology,"_GO.pdf"))
                  }
                }
                
                invisible(grpGO)
}

```


```{r GO annot, message=FALSE, warning = FALSE, include= FALSE, out.width = '60%', eval =FALSE}

lapply(X = unique(res.bsc_clusters$clust), FUN = function(x){
  lapply(X = c("BP","CC","MF"), FUN = function(y){
    DEGClusterGO(res.bsc, res.bsc_clusters, clust = x, ontology = y, plot = TRUE, save = TRUE)
  })
})


lapply(X = unique(res.pvc_clusters$clust), FUN = function(x){
  lapply(X = c("BP","CC","MF"), FUN = function(y){
    DEGClusterGO(res.pvc, res.pvc_clusters, clust = x, ontology = y, plot = TRUE, save = TRUE)
  })
})


# ug <- usedGO(GOdata)
# sel.terms <- sample(usedGO(GOdata), 10)
# genesInTerm(GOdata, "GO:0002673")





```


## Annotation Rates
```{r}

AcTxAnot %>% nrow()
AcTxAnot %>% filter(tx %in% rownames(res.bsc)) %>% unique() %>% nrow()

Tx2Prot2Kegg %>% select(ko,tx) %>% filter(tx %in% rownames(res.bsc) & ko != "") %>% unique() %>% nrow()


lapply(unique(res.pvc_clusters$clust), FUN = function(x){
  
  filt <- res.pvc_clusters %>% filter(clust == x)
  uni <- AcTxAnot %>% filter(tx%in% filt$genes)
  kegg <- Tx2Prot2Kegg %>% filter(tx %in% filt$genes) %>% filter(ko != "")
  
  paste0(x," n: ",nrow(filt) ," KEGG: ", nrow(kegg)," (", round(nrow(kegg)/nrow(filt)*100,1), "%)",
         " | UNIPROT: ", nrow(uni)," (", round(nrow(uni)/nrow(filt)*100,1),"%)"
  )
  
})


filt <- res.bsc %>% rownames_to_column("tx") %>% filter(padj <= 0.01)
uni <- AcTxAnot %>% filter(tx%in% filt$tx)
kegg <- Tx2Prot2Kegg %>% filter(tx %in% filt$tx) %>% filter(ko != "")
  
paste0(" n: ",nrow(filt) ," KEGG: ", nrow(kegg)," (", round(nrow(kegg)/nrow(filt)*100,1), "%)",
         " | UNIPROT: ", nrow(uni)," (", round(nrow(uni)/nrow(filt)*100,1),"%)" )






```

